# areas
"area: examples":
  - any: ["examples/*", "examples/**/*"]

"area: turborepo":
  - any: ["cli/*"]
  - any: ["crates/turborepo/*"]
  - any: ["crates/turborepo-lib/*"]

"area: turbopack":
  - any:
      [
        "crates/**/*",
        "!crates/turborepo/*",
        "!crates/turborepo/**/*",
        "!crates/turborepo-lib/*",
        "!crates/turborepo-lib/**/*",
      ]

"area: site":
  - any: ["docs/*"]
  - all: ["docs/**/*", "!docs/**/*.mdx"]

"area: ci":
  - any: [".github/*", ".github/**/*"]

"area: docs":
  - any: ["docs/*"]
  - all: ["docs/**/*", "docs/**/*.mdx"]

# packages
"pkg: create-turbo":
  - "packages/create-turbo/*"
  - "packages/create-turbo/**/*"

"pkg: turbo-eslint":
  - "packages/eslint-config-turbo/*"
  - "packages/eslint-config-turbo/**/*"
  - "packages/eslint-plugin-turbo/*"
  - "packages/eslint-plugin-turbo/**/*"

"pkg: turbo-ignore":
  - "packages/turbo-ignore/*"
  - "packages/turbo-ignore/**/*"

"pkg: turbo-codemod":
  - "packages/turbo-codemod/*"
  - "packages/turbo-codemod/**/*"
