name: Create PR

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Staging branch to run release from"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
        with:
          ref: ${{ inputs.release_branch }}
      - name: Get version
        id: getVersion
        run: echo ::set-output name=version::$(head -n 1 version.txt)
      - name: Test output
        run: echo ${{ steps.getVersion.outputs.version }}
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ inputs.release_branch }}
          base: main
          title: "release(turborepo): ${{ steps.getVersion.outputs.version }}"
