name: Smoke Test Canary

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test-local:
    name: "Test local turbo"
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.1
      - name: Checkout test file
        uses: Bhacaz/checkout-files@v2
        with:
         files: scripts/smoke-canary.js
      - name: Run Test
        run: node scripts/smoke-canary.js local canary pnpm
