name: Smoke Test Canary

on:
  workflow_dispatch:

jobs:
  test-local:
    name: "Test local turbo"
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.1
      - name: Setup Basic Example
        run: npx create-turbo@canary --help --use-pnpm .
      - name: Check turbo bin
        id: turbo-bin
        run: |
          echo "turbo_bin=$(pnpm turbo bin)" >> $GITHUB_ENV
      - name: Verify binary location
        uses: nick-fields/assert-action@v1
        with:
          expected: global
          actual: ${{ env.turbo_bin }}
          comparison: notContains
      - name: Build
        id: turbo-build-1
        run: |
          echo "turbo_build_1=$(pnpm turbo build)" >> $GITHUB_ENV
      - name: Build Again (Cache Hit)
        id: turbo-build-2
        run: |
          echo "turbo_build_2=$(pnpm turbo build)" >> $GITHUB_ENV
      - name: Verify first build result
        uses: nick-fields/assert-action@v1
        with:
          expected: "FULL TURBO"
          actual: ${{ env.turbo_build_1 }}
          comparison: notContains 
      - name: Verify full turbo
        uses: nick-fields/assert-action@v1
        with:
          expected: "FULL TURBO"
          actual: ${{ env.turbo_build_2 }}
          comparison: contains 
#   test-global:
#     name: "Test global turbo"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2.2.4
#         with:
#           version: 7.12.1
#       - name: Setup Global Turbo
#         run: pnpm install turbo@canary --global
#       - name: Setup Basic Example
#         run: npx create-turbo@canary --help --use-pnpm .
#       - name: Check turbo bin
#         run: turbo bin
#       - name: Remove Local Turbo
#         run: pnpm uninstall turbo
#       - name: Check turbo bin
#         run: turbo bin
#       - name: Build
#         run: turbo build
#       - name: Build Again (Cache Hit)
#         run: turbo build
#   test-both:
#     name: "Test global & local turbo (inference)"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2.2.4
#         with:
#           version: 7.12.1
#       - name: Setup Global Turbo
#         run: pnpm install turbo@canary --global
#       - name: Setup Basic Example
#         run: npx create-turbo@canary --help --use-pnpm .
#       - name: Check turbo bin
#         run: turbo bin
#       - name: Build
#         run: turbo build
#       - name: Build Again (Cache Hit)
#         run: turbo build
