name: Smoke Test Canary

on:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
        with:
          enable-corepack: false
      - name: Setup Basic Example
        run: npx create-turbo@latest --help --use-pnpm basic-test
      - name: Build
        run: cd basic-test && pnpm build
