name: Smoke Test Canary

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test_matrix:
    name: "Smoke Test Canary"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["local", "global", "both"]
        packageManager: ["npm", "pnpm"]
        
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.1
      - name: Checkout test file
        uses: Bhacaz/checkout-files@v2
        with:
         files: scripts/smoke-canary.js
      - name: Run Test
        run: node scripts/smoke-canary.js ${{ matrix.test }} canary ${{ matrix.packageManager }}
