name: Smoke Test Canary

on:
  workflow_dispatch:

jobs:
  test-local:
    name: "test local turbo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
        with:
          enable-corepack: false
      - name: Setup Basic Example
        run: npx create-turbo@canary --help --use-pnpm basic-test
      - name: Build
        run: cd basic-test && pnpm build
  test-global:
    name: "test global turbo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
        with:
          enable-corepack: false
      - name: Setup Global Turbo
        run: pnpm install turbo@canary --global
      - name: Setup Basic Example
        run: npx create-turbo@canary --help --use-pnpm basic-test
      - name: Remove Local Turbo
        run: cd basic-test && pnpm uninstall turbo
      - name: Build
        run: pnpm build
