name: Smoke Test Canary

on:
  workflow_dispatch:

jobs:
  test-local:
    name: "test local turbo"
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node
        with:
          enable-corepack: false
      - name: Setup Basic Example
        run: npx create-turbo@canary --help --use-pnpm basic-test
      - name: Enter project directory
        run: cd ./basic-test
      - name: Check turbo bin
        run: pwd && pnpm turbo bin
      - name: Build
        run: pnpm turbo build
  test-global:
    name: "test global turbo"
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node
        with:
          enable-corepack: false
      - name: Setup Global Turbo
        run: pnpm install turbo@canary --global
      - name: Setup Basic Example
        run: npx create-turbo@canary --help --use-pnpm basic-test
      - name: Enter project directory
        run: cd ./basic-test
      - name: Check turbo bin
        run: pwd && turbo bin
      - name: Remove Local Turbo
        run: pnpm uninstall turbo
      - name: Check turbo bin
        run: turbo bin
      - name: Build
        run: turbo build
